name: CI

on: 
  push:

jobs:
    quality:
      runs-on: ubuntu-latest
      steps:
        - name: verification
          uses: actions/checkout@v4 

        - name: configuration_biome
          uses: biomejs/setup-biome@v2
          with:
            version: "2.0.5"

        - name: execution
          run: "biome ci ."

    test:
      runs-on: ubuntu-latest
      needs: quality
      steps:
        - name: verification
          uses: actions/checkout@v4
        
        - name: configuration_bun
          uses: oven-sh/setup-bun@v2

        - name: install_dependance_bun
          run: "bun install --frozen-lockfile"

        - name: test bun
          run: "bun test"
          